### ISSUE TITLE
Minor issue in paper

### ISSUE THREAD

**Issue by sarahESL** [haifangong/CMSA-MTPT-4-MedicalVQA#1]
Nice work, thanks for sharing it publicly.

Just wanted to point out a minor issue/typo in the paper. The references in Table 1 do not seem to be correct and should be updated to 14, 17 and 29 (as correctly written in section 4.2), respectively.

**Comment by haifangong** [comment]
Thank you for your advice very much, we have correct the citation error in the camera-ready version.
