### ISSUE TITLE
您好，请问可以分享个预训练数据集的百度网盘链接吗？

### ISSUE THREAD

**Issue by lycutter** [haifangong/CMSA-MTPT-4-MedicalVQA#5]
我们校园网这里下不到Abdomen的数据集，请问您可以通过百度网盘分享下吗，非常感谢！

**Comment by haifangong** [comment]
We have released the link to the dataset on Baidu Drive and Google Drive in the newest version of the README file.

**Comment by lycutter** [comment]
> M

非常感谢，之前没留意，抱歉
