### ISSUE TITLE
pre-train problem

### ISSUE THREAD

**Issue by Edwina-coco** [haifangong/CMSA-MTPT-4-MedicalVQA#6]
Hello,I was a little confused when I was looking at your pretraining code recently:
1. utils.cal_acc and utils.cal_iou in the pre-training code are not given.
2. the pre-trained train file is not given, only eval.
3. how do I pre train my model？
Looking forward to your reply

**Comment by haifangong** [comment]
Sorry for the late reply. These files are now available under the multi-task pretrain folder.

**Comment by Edwina-coco** [comment]
> Sorry for the late reply. These files are now available under the multi-task pretrain folder.

ok，thanks
